name: Generate RSS feed

on:
  workflow_dispatch:    # Allows manual run
  schedule:
    - cron: "0 6 * * *"  # Runs every day at 6am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feed
        run: python generate_rss.py

      - name: Commit and push RSS
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes to commit"
          git push
